# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9adbb020c825beabeeebaab64c3bd3cd2b548fa6688847672190243c78a726010b0301fa6c3495d9d9e3f65b79d35fbbb32356cb22565b4536125b8585bc8fb1

test:
  secret_key_base: 3107a5fd17b97a38ec32dcd7618ea04467a1f1c4c38269d5b87858b4e5578d28a10a3cf0d5675b02946f7d7d1251583c41c66121764a002384f71c517e5799f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
